#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=20
#SBATCH --mem=150G
#SBATCH --time=24:00:00
#SBATCH --qos=gpu
#SBATCH --partition=u1-h100
#SBATCH --output=/scratch3/BMC/gpu-ghpcs/Rey.Koki/Cloud_Top_Temp/deep_learning/logs/deep_learning.%j.log
#SBATCH --account=gpu-ghpcs

module purge
module load cuda

source /scratch3/BMC/gpu-ghpcs/Rey.Koki/miniconda/etc/profile.d/conda.sh 
conda activate cloud 
sleep 2h
## python main.py $CONFIG_FN
exit 0

